"""Locations shared by the pipeline scripts. Override the two inputs with environment variables."""
import os

REPO = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))

# MAV-Celeb root: the folder holding v1/, v2/, v3/, each with voices/ (and faces/ for the teachers).
DATA_ROOT = os.environ.get("MAVCELEB_DATA_ROOT", os.path.join(REPO, "mavceleb"))
# Raw teacher outputs: poster/mavceleb_v{N}/*.npz (label_poster.py), senet/mavceleb_v{N}/*.csv (dump_frames_senet.m).
TEACHER_ROOT = os.environ.get("MAVCELEB_TEACHER_ROOT", os.path.join(REPO, "teacher_outputs"))

CLIP_LABELS = os.path.join(REPO, "data", "clip_labels.csv")   # shipped with the repo
SPLITS = os.path.join(REPO, "data", "splits")                  # generated by build_splits.py
RUNS = os.path.join(REPO, "runs")                              # checkpoints + eval JSONs
RESULTS = os.path.join(REPO, "results")                        # tables (+ the paper's eval JSONs)
STUDENT = os.path.join(REPO, "student")

VERSIONS = ["v1", "v2", "v3"]
PAIRS = {"v1": "urdu", "v2": "hindi", "v3": "german"}        # each version: English + one paired language
# POSTER V2 / AffectNet-8 order, used for all label columns
POSTER_ORDER = ["neutral", "happiness", "sadness", "surprise", "fear", "disgust", "anger", "contempt"]
